version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: counterproject-db
    environment:
      POSTGRES_DB: counterproject
      POSTGRES_USER: counterproject
      POSTGRES_PASSWORD: counterproject
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U counterproject"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    container_name: counterproject-backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: counterproject
      DB_USER: counterproject
      DB_PASSWORD: counterproject
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    container_name: counterproject-frontend
    ports:
      - "8000:80"
    depends_on:
      - backend

volumes:
  db-data:
